export const REDIRECT_NOTFOUND  = 'REDIRECT_NOTFOUND';
export const IDENTITY_LOGIN  = 'IDENTITY_LOGIN';
export const IDENTITY_FETCH  = 'IDENTITY_FETCH';
export const IDENTITY_LOGOUT  = 'IDENTITY_LOGOUT';
export const IDENTITY_UPDATE  = 'IDENTITY_UPDATE';
export const DECODE_TOKEN  = 'DECODE_TOKEN';
export const ACCOUNT_SAVEUSER  = 'ACCOUNT_SAVEUSER';
export const IDENTITY_AUTHENTICATION  = 'IDENTITY_AUTHENTICATION';
