export const IDENTITY_REMOVEUSERPROPS  = 'IDENTITY_REMOVEUSERPROPS';
export const IDENTITY_SAVEUSERPROPS = 'IDENTITY_SAVEUSERPROPS';
export const IDENTITY_UPDATEUSERPROPS  = 'IDENTITY_UPDATEUSERPROPS';
export const IDENTITY_SAVETENANTID  = 'IDENTITY_SAVETENANTID';
